#include "platform.h"

#include <dlfcn.h>
#include <errno.h>
#include <limits.h>
#include <pthread.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/un.h>
#include <time.h>
#include <unistd.h>

/* Embedded payloads — generated by xxd at build time. */
extern const unsigned char raven_payload_forge[];
extern const unsigned int  raven_payload_forge_len;
extern const unsigned char raven_payload_lunar[];
extern const unsigned int  raven_payload_lunar_len;

static int g_progress_fd = -1;

/* ---- Logging ------------------------------------------------------------ */

void raven_log(const char *format, ...) {
    char message[2048];
    char line[2304];
    char log_path[PATH_MAX];
    char dir[PATH_MAX];
    struct timespec ts;
    struct tm tm;
    FILE *file;
    va_list args;

    va_start(args, format);
    vsnprintf(message, sizeof(message), format, args);
    va_end(args);

    clock_gettime(CLOCK_REALTIME, &ts);
    localtime_r(&ts.tv_sec, &tm);
    snprintf(line, sizeof(line),
            "[%04d-%02d-%02d %02d:%02d:%02d.%03ld] %s\n",
            tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday,
            tm.tm_hour, tm.tm_min, tm.tm_sec,
            ts.tv_nsec / 1000000, message);
    fputs(line, stderr);

    if (raven_module_directory(dir, sizeof(dir))) {
        snprintf(log_path, sizeof(log_path), "%s/raven-native.log", dir);
        file = fopen(log_path, "a");
        if (file) {
            fputs(line, file);
            fclose(file);
        }
    }
}

void raven_log_wide(const char *format, ...) {
    char buf[2048];
    va_list args;
    va_start(args, format);
    vsnprintf(buf, sizeof(buf), format, args);
    va_end(args);
    raven_log("%s", buf);
}

/* ---- Progress ----------------------------------------------------------- */

void raven_progress_init(void) {
    const char *path = getenv("MINDLESS_PROGRESS_SOCKET");
    struct sockaddr_un addr;
    if (!path || !path[0]) return;

    g_progress_fd = socket(AF_UNIX, SOCK_STREAM, 0);
    if (g_progress_fd < 0) return;

    memset(&addr, 0, sizeof(addr));
    addr.sun_family = AF_UNIX;
    strncpy(addr.sun_path, path, sizeof(addr.sun_path) - 1);

    if (connect(g_progress_fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        close(g_progress_fd);
        g_progress_fd = -1;
    }
}

void raven_progress_send(float progress, const char *status) {
    char message[512];
    int len;
    if (g_progress_fd < 0) return;
    len = snprintf(message, sizeof(message), "PROGRESS:%f:%s\n",
            progress, status ? status : "");
    if (len > 0) {
        (void)write(g_progress_fd, message, (size_t)len);
    }
}

void raven_progress_close(void) {
    if (g_progress_fd >= 0) {
        close(g_progress_fd);
        g_progress_fd = -1;
    }
}

/* ---- Threading ---------------------------------------------------------- */

struct thread_wrapper_ctx {
    raven_thread_fn fn;
    void *arg;
};

static void *thread_wrapper(void *ctx) {
    struct thread_wrapper_ctx *w = (struct thread_wrapper_ctx *)ctx;
    w->fn(w->arg);
    free(w);
    return NULL;
}

int raven_thread_create(raven_thread_fn fn, void *arg) {
    pthread_t tid;
    struct thread_wrapper_ctx *ctx = malloc(sizeof(*ctx));
    if (!ctx) return 0;
    ctx->fn = fn;
    ctx->arg = arg;
    if (pthread_create(&tid, NULL, thread_wrapper, ctx) != 0) {
        free(ctx);
        return 0;
    }
    pthread_detach(tid);
    return 1;
}

/* ---- Misc --------------------------------------------------------------- */

void raven_sleep_ms(unsigned int ms) {
    struct timespec ts = { ms / 1000, (ms % 1000) * 1000000L };
    nanosleep(&ts, NULL);
}

long raven_atomic_cmpxchg(volatile long *target, long expected, long desired) {
    __atomic_compare_exchange_n(target, &expected, desired, 0,
            __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
    return expected;
}

long raven_atomic_exchange(volatile long *target, long value) {
    return __atomic_exchange_n(target, value, __ATOMIC_SEQ_CST);
}

/* ---- Module path -------------------------------------------------------- */

int raven_module_directory(char *output, size_t capacity) {
    Dl_info info;
    char *sep;
    if (!dladdr((void *)raven_module_directory, &info) || !info.dli_fname)
        return 0;
    if (strlen(info.dli_fname) >= capacity) return 0;
    strncpy(output, info.dli_fname, capacity);
    output[capacity - 1] = '\0';
    sep = strrchr(output, '/');
    if (!sep) return 0;
    *sep = '\0';
    return 1;
}

/* ---- Payload extraction ------------------------------------------------- */

int raven_extract_payload(int resource_id, const char *profile_name,
        char *jar_path, size_t jar_capacity) {
    const unsigned char *data;
    unsigned int size;
    char tmp_dir[PATH_MAX];
    FILE *file;

    if (resource_id == RAVEN_PAYLOAD_FORGE) {
        data = raven_payload_forge;
        size = raven_payload_forge_len;
    } else if (resource_id == RAVEN_PAYLOAD_LUNAR) {
        data = raven_payload_lunar;
        size = raven_payload_lunar_len;
    } else {
        raven_log("unknown payload resource id: %d", resource_id);
        return 0;
    }

    if (size < 4 || data[0] != 'P' || data[1] != 'K') {
        raven_log("embedded payload is invalid");
        return 0;
    }

    snprintf(tmp_dir, sizeof(tmp_dir), "/tmp/RavenNative");
    mkdir(tmp_dir, 0755);

    snprintf(jar_path, jar_capacity, "%s/raven-%s-payload-%d.jar",
            tmp_dir, profile_name, getpid());

    file = fopen(jar_path, "wb");
    if (!file) {
        raven_log("failed to create payload file: %s", strerror(errno));
        return 0;
    }
    if (fwrite(data, 1, size, file) != size) {
        raven_log("failed to write payload file");
        fclose(file);
        unlink(jar_path);
        return 0;
    }
    fclose(file);
    raven_log("materialized payload: %s (%u bytes)", jar_path, size);
    return 1;
}

/* ---- JVM discovery ------------------------------------------------------ */

JavaVM *raven_find_jvm(void) {
    typedef jint (JNICALL *get_created_vms_fn)(JavaVM **, jsize, jsize *);
    void *libjvm;
    get_created_vms_fn get_created_vms;
    JavaVM *vm = NULL;
    jsize count = 0;

    libjvm = dlopen("libjvm.so", RTLD_NOLOAD | RTLD_LAZY);
    if (!libjvm) return NULL;

    get_created_vms = (get_created_vms_fn)dlsym(libjvm, "JNI_GetCreatedJavaVMs");
    if (!get_created_vms) {
        dlclose(libjvm);
        return NULL;
    }

    if (get_created_vms(&vm, 1, &count) != JNI_OK || count < 1) {
        dlclose(libjvm);
        return NULL;
    }
    dlclose(libjvm);
    return vm;
}

/* ---- Library constructor (entry point on load) -------------------------- */

static void bootstrap_entry(void *arg);

__attribute__((constructor))
static void raven_init(void) {
    raven_thread_create(bootstrap_entry, NULL);
}

/* Forward declaration — implemented in bootstrap.c */
extern void raven_bootstrap_main(void *arg);

static void bootstrap_entry(void *arg) {
    (void)arg;
    raven_bootstrap_main(NULL);
}
